version: '3.7'

services:
  web:
    image: music-feedback-website
    secrets:
      - my_env_file
    deploy:
      replicas: 3
    ports:
      - "8080:80

secrets:
  my_env_file:
    external: true