version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: music-feedback-website
    env_file:
      - ./config/.env
    volumes:
      - /Users/doll/Desktop/programming/MF-Server-Webpage/config/.env:/my_project/.env:ro
      - .:/var/www/html
    ports:
      - "80:80"
