version: '3'
services:
  web:
    build:
      image: jdollx/music-feedback-website
      context: . 
      dockerfile: Dockerfile
    volumes:
      - ./config:/var/www/html/config
    ports:
      - "8082:80"