name: Docker Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        env:
          USE: ${{ secrets.USE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DISCORDWIDGET: ${{ secrets.DISCORDWIDGET }}
          email: ${{ secrets.email }}
          email_password: ${{ secrets.email_password }}
          TOKEN: ${{ secrets.TOKEN }}
          JENN_ID: ${{ secrets.JENN_ID }}
          MAKI_ID: ${{ secrets.MAKI_ID }}
          STRIKE_ID: ${{ secrets.STRIKE_ID }}
          SONO_ID: ${{ secrets.SONO_ID }}
          TAV_ID: ${{ secrets.TAV_ID }}
          DAVID_ID: ${{ secrets.DAVID_ID }}
          AMAZE_ID: ${{ secrets.AMAZE_ID }}
          TOAST_ID: ${{ secrets.TOAST_ID }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
        run: docker build -t music-feedback-website .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push music-feedback-website
