name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Print Docker Username
        run: printf "Docker Username: %s\n" "${{ secrets.DOCKER_USERNAME }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build \
          --file Dockerfile \
          --tag jdollx/music-feedback-website:$(date +%s) \
          .

      - name: Push the Docker image to Docker Hub
        run: |
          docker tag jdollx/music-feedback-website:$(date +%s) jdollx/music-feedback-website:latest
          docker push jdollx/music-feedback-website:latest
