name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build --tag jdollx/music-feedback-website .
        docker push jdollx/music-feedback-website

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Docker container
      run: |
        docker run -d \
          -e USE="${{ secrets.USE }}" \
          -e PASSWORD="${{ secrets.PASSWORD }}" \
          -e DISCORDWIDGET="${{ secrets.DISCORDWIDGET }}" \
          -e EMAIL="${{ secrets.EMAIL }}" \
          -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
          -e TOKEN="${{ secrets.TOKEN }}" \
          -e JENN_ID="${{ secrets.JENN_ID }}" \
          -e MAKI_ID="${{ secrets.MAKI_ID }}" \
          -e STRIKE_ID="${{ secrets.STRIKE_ID }}" \
          -e SONO_ID="${{ secrets.SONO_ID }}" \
          -e TAV_ID="${{ secrets.TAV_ID }}" \
          -e DAVID_ID="${{ secrets.DAVID_ID }}" \
          -e AMAZE_ID="${{ secrets.AMAZE_ID }}" \
          -e TOAST_ID="${{ secrets.TOAST_ID }}" \
          -e SERVER_ID="${{ secrets.SERVER_ID }}" \
          jdollx/music-feedback-website
