name: Docker Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        env:
          USE: ${{ secrets.USE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DISCORDWIDGET: ${{ secrets.DISCORDWIDGET }}
          EMAIL: ${{ secrets.email }}
          EMAIL_PASSWORD: ${{ secrets.email_password }}
          TOKEN: ${{ secrets.TOKEN }}
          JENN_ID: ${{ secrets.JENN_ID }}
          MAKI_ID: ${{ secrets.MAKI_ID }}
          STRIKE_ID: ${{ secrets.STRIKE_ID }}
          SONO_ID: ${{ secrets.SONO_ID }}
          TAV_ID: ${{ secrets.TAV_ID }}
          DAVID_ID: ${{ secrets.DAVID_ID }}
          AMAZE_ID: ${{ secrets.AMAZE_ID }}
          TOAST_ID: ${{ secrets.TOAST_ID }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
        run: |
          docker buildx build \
            --build-arg USE=${{ env.USE }} \
            --build-arg PASSWORD=${{ env.PASSWORD }} \
            --build-arg DISCORDWIDGET=${{ env.DISCORDWIDGET }} \
            --build-arg EMAIL=${{ env.EMAIL }} \
            --build-arg EMAIL_PASSWORD=${{ env.EMAIL_PASSWORD }} \
            --build-arg TOKEN=${{ env.TOKEN }} \
            --build-arg JENN_ID=${{ env.JENN_ID }} \
            --build-arg MAKI_ID=${{ env.MAKI_ID }} \
            --build-arg STRIKE_ID=${{ env.STRIKE_ID }} \
            --build-arg SONO_ID=${{ env.SONO_ID }} \
            --build-arg TAV_ID=${{ env.TAV_ID }} \
            --build-arg DAVID_ID=${{ env.DAVID_ID }} \
            --build-arg AMAZE_ID=${{ env.AMAZE_ID }} \
            --build-arg TOAST_ID=${{ env.TOAST_ID }} \
            --build-arg SERVER_ID=${{ env.SERVER_ID }} \
            -t music-feedback-website \
            .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag music-feedback-website $DOCKER_USERNAME/music-feedback-website:latest
          docker push $DOCKER_USERNAME/music-feedback-website:latest
