name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build the Docker image
      run: docker build \
        --file Dockerfile \
        --tag Jdollx/music-feedback-website:$(date +%s) \
        .

    - name: Push the Docker image to Docker Hub
      run: |
        docker tag Jdollx/music-feedback-website:$(date +%s) Jdollx/music-feedback-website:latest
        docker push Jdollx/music-feedback-website:latest
