name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker images
      run: |
        docker build -t music-feedback-website .
        docker push music-feedback-website

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy with Docker
      env:
        USE: ${{ secrets.USE }}
        PASSWORD: ${{ secrets.PASSWORD }}
        DISCORDWIDGET: ${{ secrets.DISCORDWIDGET }}
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TOKEN: ${{ secrets.TOKEN }}
        JENN_ID: ${{ secrets.JENN_ID }}
        MAKI_ID: ${{ secrets.MAKI_ID }}
        STRIKE_ID: ${{ secrets.STRIKE_ID }}
        SONO_ID: ${{ secrets.SONO_ID }}
        TAV_ID: ${{ secrets.TAV_ID }}
        DAVID_ID: ${{ secrets.DAVID_ID }}
        AMAZE_ID: ${{ secrets.AMAZE_ID }}
        TOAST_ID: ${{ secrets.TOAST_ID }}
        SERVER_ID: ${{ secrets.SERVER_ID }}
      run: |
        docker run \
          --env USE=${{ secrets.USE }} \
          --env PASSWORD=${{ secrets.PASSWORD }} \
          --env DISCORDWIDGET=${{ secrets.DISCORDWIDGET }} \
          --env EMAIL=${{ secrets.EMAIL }} \
          --env EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
          --env TOKEN=${{ secrets.TOKEN }} \
          --env JENN_ID=${{ secrets.JENN_ID }} \
          --env MAKI_ID=${{ secrets.MAKI_ID }} \
          --env STRIKE_ID=${{ secrets.STRIKE_ID }} \
          --env SONO_ID=${{ secrets.SONO_ID }} \
          --env TAV_ID=${{ secrets.TAV_ID }} \
          --env DAVID_ID=${{ secrets.DAVID_ID }} \
          --env AMAZE_ID=${{ secrets.AMAZE_ID }} \
          --env TOAST_ID=${{ secrets.TOAST_ID }} \
          --env SERVER_ID=${{ secrets.SERVER_ID }} \
          -p 8080:80 \
          music-feedback-website
