name: Docker Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/music-feedback-website:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/music-feedback-website:latest

      - name: Run Docker Container
        env:
          USE: ${{ secrets.USE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DISCORDWIDGET: ${{ secrets.DISCORDWIDGET }}
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TOKEN: ${{ secrets.TOKEN }}
          JENN_ID: ${{ secrets.JENN_ID }}
          MAKI_ID: ${{ secrets.MAKI_ID }}
          STRIKE_ID: ${{ secrets.STRIKE_ID }}
          SONO_ID: ${{ secrets.SONO_ID }}
          TAV_ID: ${{ secrets.TAV_ID }}
          DAVID_ID: ${{ secrets.DAVID_ID }}
          AMAZE_ID: ${{ secrets.AMAZE_ID }}
          TOAST_ID: ${{ secrets.TOAST_ID }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
        run: |
          docker run -d \
            -e USE="$USE" \
            -e PASSWORD="$PASSWORD" \
            -e DISCORDWIDGET="$DISCORDWIDGET" \
            -e EMAIL="$EMAIL" \
            -e EMAIL_PASSWORD="$EMAIL_PASSWORD" \
            -e TOKEN="$TOKEN" \
            -e JENN_ID="$JENN_ID" \
            -e MAKI_ID="$MAKI_ID" \
            -e STRIKE_ID="$STRIKE_ID" \
            -e SONO_ID="$SONO_ID" \
            -e TAV_ID="$TAV_ID" \
            -e DAVID_ID="$DAVID_ID" \
            -e AMAZE_ID="$AMAZE_ID" \
            -e TOAST_ID="$TOAST_ID" \
            -e SERVER_ID="$SERVER_ID" \
            -p 8080:80 \
            --name music-feedback-website \
            ${{ secrets.DOCKER_USERNAME }}/music-feedback-website:latest
