name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build the Docker image
        run: docker build \
          --file Dockerfile \
          --tag jdollx/music-feedback-website:$(date +%s) \
          .

      - name: Push the Docker image to Docker Hub
        run: |
          docker tag jdollx/music-feedback-website:$(date +%s) jdollx/music-feedback-website:latest
          docker push jdollx/music-feedback-website:latest
