name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Push Multi-Architecture Docker Image
        run: |
          docker buildx build \
            --file Dockerfile \
            --tag jdollx/music-feedback-website:$(date +%s) \
            --tag jdollx/music-feedback-website:latest \
            --push \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            .
